name: GitHub Box

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: master

jobs:
  update-gist:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: zoispag/gh-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          CONSIDER_PRIVATE: true
